### PR TITLE
serverinstall/nomad: Spend more time looking at waypoint-runner allocation on install to ensure start up

### LINKED ISSUE #2683: serverinstall/nomad: Spend more time looking at `waypoint-runner` allocation on install to ensure start up
**Describe the bug**

Currently the server install command for the Nomad platform spins waiting for the `waypoint-runner` job to be "created" and "running", and then exits immediately when that job enters these states. One issue with this is with the recent addition of Consul, if the runner cannot properly resolve the Consul DNS the runner job passes the created and running states, but soon after the container exits due to not making a successful connection to Waypoint server because it couldn't resolve the Consul DNS hostname.

Ideally, we should fix up the server install function for Nomad to not only wait until the job is running, but also ensure the jobs container in the allocation successfully connects back to Waypoint server before calling the install "successful". Note that this failure happens almost immediately after the job is running, so waiting a bit longer and doing a few more cycles to check the container is healthy and running should be enough.

**Steps to Reproduce**

Install Waypoint server to Nomad with misconfigured Consul DNS, see that the waypoint-runner exits due to failing to connect back to Waypoint server.

**Expected behavior**

Update the install runner function to also ensure the container is successfully running beyond the first check.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.6.2
* Waypoint Server Platform and Version: Nomad, 0.6.2+
* Waypoint Plugin: n/a

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, the server install command would look for the very
first instance for when an allocation was considered running. This is
generally ok, however if the Nomad job fails to get started a moment
later (like a static runner failing to connect back to Waypoint Server),
the runner allocation would exit later but the server install command
would consider the installation successful.

This is especially important when users are configuring Consul DNS
with Waypoint Server installed to Nomad. The static runner might
fail to properly make a connection through the Consul DNS hostname
and fail, leaving the installation without a static runner but the CLI claiming
the install succeeded.

This commit fixes that by doing a few retries for a few seconds on the scheduled
allocation once its in a "running" state to validate it properly started
up beyond the first few moments of the job.

Fixes #2683

### CODE REVIEW

File: internal/serverinstall/nomad.go [hunk 1]
```diff
@@ -802,7 +787,12 @@ EVAL:
 		}
 
 		if allocID != "" {
-			return allocID, nil
+			if retries == maxRetries {
+				return allocID, nil
+			} else {
+				s.Update("Ensuring allocation %q has properly started up...", allocs[0].ID)
+				time.Sleep(1 * time.Second)
+			}
```
Comment (evanphx) [inline internal/serverinstall/nomad.go:795]: Because we move the WaitIndex forward before trying again, won't the call to Allocations wait more than 1 second if the allocation is running fine, because there won't be any updates to report, so the call won't return?

File: internal/serverinstall/nomad.go [hunk 2]
```diff
@@ -756,30 +748,22 @@ func (i *NomadInstaller) runJob(
 	}
 
 	s.Update("Waiting for allocation to be scheduled")
-EVAL:
 	qopts := &api.QueryOptions{
```
Comment (evanphx) [inline internal/serverinstall/nomad.go:751]: Related to my later comment, we probably need to be setting the WaitTime (or whatever it's called) on this so that we don't block indefinitely on these calls, but rather wait some amount of time before we figure out if we want to continue waiting.

File: internal/serverinstall/nomad.go (hunk 1 above)
Comment (briancain) [reply internal/serverinstall/nomad.go:795]: From what I could tell, the call to Allocations uses a default `WaitTime` if none specified, but I can set a more explicit one of 500 milliseconds to be sure. From my testing in the positive case, the call always returned after the ~3 seconds this loop retries on.

File: internal/serverinstall/nomad.go (hunk 2 above)
Comment (briancain) [reply internal/serverinstall/nomad.go:752]: The API tells me they use a default `WaitTime`, so we shouldn't be blocking forever. I set a default one anyway to be sure.

**Review by krantzinator — APPROVED** [review]
Looks like this will be a bit friendlier UX when errors happen!

File: internal/serverinstall/nomad.go (hunk 1 above)
Comment (evanphx) [reply internal/serverinstall/nomad.go:797]: The change looks good!

**Review by evanphx — APPROVED** [review]
