### PR TITLE
ui: added sidebar/panel ui to deployments tab

### LINKED ISSUE #2539: ui: `<StatusReportMetaTable>` alignment is slightly off
**Describe the bug**
The values in the table are set ever-so-slightly low relative to the headings:

CleanShot 2021-10-21 at 13 57 18@2x

**Steps to Reproduce**
1. Boot the dev server (`cd ui && yarn start`)
2. [Visit a deployment page](http://localhost:4200/default/marketing-public/app/wp-matrix/deployment/seq/4)
3. Observe the issue

**Expected behavior**
Row heading and values should share a baseline.

**Waypoint Platform Versions**
0fd4ce0c9100d4a3a2c79e01e18e367a2a83437e

### LINKED ISSUE #2614: ui: Change UX of deployment's details from separate page to sidebar/panel design
see: New design files for further information

Currently when you want to see the details of a specific deployment, you are routed to an entirely new page. We want instead for a main panel to re-render whenever a different deployment is chosen in a sidebar panel, and have the rest of the application overview screen stay.

### PR DESCRIPTION
**Pull request by sabrinako**
## Screenshot
Screen Shot 2021-11-23 at 3 31 37 PM

## Notes
- Build + release tabs are actually going to be in a different table format, so this PR just changes the deployments tab
- Changes to paths
  - The sidebar view that outlets to the details page is now the `deployment` route/template
  - The details page is the `deployment/deployment-seq` route/template
  - `deployments` route exists just to redirect to the `deployment` route
  - There's obviously some changes, but a lot of the code was just relocated
  - `StatusReportMetaTable` alignment is fixed (but this could have been from a previous PR and I just didn't notice)

## How to test
1. Pull down this branch `git checkout ui/sidebar-panel`
2. `yarn` (new `ember-route-helpers` dependency)
3. `yarn start`
4. Navigate to the deployments tab (should automatically load when you select an application)
5. Make sure everything is working as expected

### CODE REVIEW

**Comment by jgwhite** [comment]
I wonder if we can boost the z-index for this state, so the outline doesn’t go below other items:

CleanShot 2021-11-24 at 10 48 44@2x

**Comment by jgwhite** [comment]
Empty state seems fine to me, but noting for other reviewers:

localhost_4200_default_empty_app_web_deployment

File: ui/app/routes/workspace/projects/project/app/deployment.ts [hunk 1]
```diff
@@ -1,43 +1,33 @@
...
-    let { deployments } = this.modelFor('workspace.projects.project.app') as AppRouteModel;
-    let deployment = deployments.find((obj) => obj.sequence == Number(params.sequence));
-
-    if (!deployment) {
-      throw new Error(`Deployment v${params.sequence} not found`);
+  afterModel(_: Model, transition: Transition): void {
+    let latestDeployment = this.modelFor(this.routeName)[0] as DeploymentExtended;
+    if (
+      latestDeployment &&
+      !transition.to.name.includes('workspace.projects.project.app.deployment.deployment-seq')
```
Comment (jgwhite) [inline ui/app/routes/workspace/projects/project/app/deployment.ts:19]: Did you experiment with putting this logic in an `deployment/index` route? Not super important, but that is the common pattern for this sort of redirect.

**Comment by almonk** [comment]
Nice to see this coming to life! There's some work to do to make this sparkle. Here's some thoughts below... For styling issues I'm always happy to pair on resolving them – just let me know.

### General styling

I've outlined some issues with the styling below.
Frame 218

List items in the overview component don't sit at equal distance from each other:
CleanShot 2021-11-24 at 10 31 52

As an side, I'm seeing some very odd resizing behaviour (probably unrelated to this PR)....

https://user-images.githubusercontent.com/51724/143221389-9fc3e930-d191-44b0-b671-64b589474180.mov

### Deployment list info

In the designs I removed all the platform info and replaced it with commit info. I know this won't always be available but maybe we should have a whiteboarding session on how this component should behave given varying levels of data.

CleanShot 2021-11-24 at 10 26 22

If we want to do that work in a different PR thats totally fine with me – we can instead focus on polishing what we have right now.

### Further design required
I'll have a think about how we can represent mutable deployments in a way that works with the reduced horizontal space. Right now this is too busy to be easily parseable I think.

CleanShot 2021-11-24 at 10 33 26

File: ui/app/routes/workspace/projects/project/app/deployments.ts [hunk 2]
```diff
@@ -1,18 +1,24 @@
...
 
-  resetController(controller: DeploymentsController, isExiting: boolean): void {
-    if (isExiting) {
-      controller.set('isShowingDestroyed', null);
+  redirect(model: Model): void {
+    if (model) {
+      if (model[0]) {
+        this.transitionTo('workspace.projects.project.app.deployment.deployment-seq', model[0].sequence);
+      }
+      this.transitionTo('workspace.projects.project.app.deployment');
```
Comment (jgwhite) [inline ui/app/routes/workspace/projects/project/app/deployments.ts:21]: For this route, I wonder if we could make it simpler, and just redirect over to `workspace.projects.project.app.deployment` and let that route take care of the redirect to the most-recent deployment.

File: ui/app/routes/workspace/projects/project/app/deployment.ts [hunk 3]
```diff
@@ -1,43 +1,33 @@
...
+    return app.deployments;
   }
 
-  async model(params: Params): Promise<Model> {
-    let { deployments } = this.modelFor('workspace.projects.project.app') as AppRouteModel;
-    let deployment = deployments.find((obj) => obj.sequence == Number(params.sequence));
-
-    if (!deployment) {
-      throw new Error(`Deployment v${params.sequence} not found`);
+  afterModel(_: Model, transition: Transition): void {
```
Comment (jgwhite) [inline ui/app/routes/workspace/projects/project/app/deployment.ts:15]: Should this be a `redirect` hook? (I never know the difference)

File: ui/app/styles/_variables.scss [hunk 4]
```diff
@@ -22,6 +22,7 @@ $button-shadow: 0 3px 2px rgba(var(--shadow), 0.2);
   --border: #{dehex(color.$ui-gray-200)};
   --outline: #{dehex(color.$ui-gray-300)};
   --card: #{dehex(color.$white)};
+  --highlighted-list-item: #{dehex(color.$ui-cool-gray-100)};
```
Comment (jgwhite) [inline ui/app/styles/_variables.scss:25]: Shall we add a dark mode color for this too?

CleanShot 2021-11-24 at 12 06 15@2x

File: ui/app/templates/workspace/projects/project/app.hbs [hunk 5]
```diff
@@ -1,11 +1,8 @@
 {{page-title @model.application.application}}
-
 {{#if (and
   (not-eq this.target.currentRouteName 'workspace.projects.project.app.build')
-  (not-eq this.target.currentRouteName 'workspace.projects.project.app.deployment')
-  (not-eq this.target.currentRouteName 'workspace.projects.project.app.release')
-  (not (includes this.target.currentRouteName 'workspace.projects.project.app.deployment.'))
-  (not (includes this.target.currentRouteName 'workspace.projects.project.app.release.'))
+  (not-eq this.target.currentRouteName 'workspace.projects.project.app.deployment.deployment-seq.resource')
+  (not-eq this.target.currentRouteName 'workspace.projects.project.app.release.resource')
```
Comment (jgwhite) [inline ui/app/templates/workspace/projects/project/app.hbs:5]: This is a satisfying simplification!

File: ui/app/templates/workspace/projects/project/app/deployment.hbs [hunk 6]
```diff
@@ -1,84 +1,44 @@
...
-            </ResourcesTable>
-          {{/if}}
-        </:body>
-      </Section>
+{{page-title (concat @model.application.application "Deployments")}}
+{{#let (not-eq this.target.currentRouteName 'workspace.projects.project.app.deployment.deployment-seq.resource') as |isNotResourcePage|}}
+  <div class={{if (and isNotResourcePage this.deploymentsByGeneration) "grid"}}>
+  {{#if isNotResourcePage}}
+    {{#if this.deploymentsByGeneration}}
+    <ul data-test-deployment-list class="sidebar list">
```
Comment (jgwhite) [inline ui/app/templates/workspace/projects/project/app/deployment.hbs:6]:
```suggestion
      <ul data-test-deployment-list class="sidebar list">
```

File: ui/app/templates/workspace/projects/project/app/deployment.hbs [hunk 7]
```diff
@@ -1,84 +1,44 @@
...
+      {{/if}}
+    {{else}}
+    <EmptyState>
+      <p>There are no deployments to display for this app yet</p>
+      <p>To create your first build, you can run
+        <CopyableCode @ref="empty-deploy" @inline="true">
+          <code id="empty-deploy">waypoint deploy</code>
+        </CopyableCode>
+        from the CLI</p>
+    </EmptyState>
```
Comment (jgwhite) [inline ui/app/templates/workspace/projects/project/app/deployment.hbs:37]:
```suggestion
      <EmptyState>
        <p>There are no deployments to display for this app yet</p>
        <p>To create your first build, you can run
          <CopyableCode @ref="empty-deploy" @inline="true">
            <code id="empty-deploy">waypoint deploy</code>
          </CopyableCode>
          from the CLI</p>
      </EmptyState>
```

File: ui/tests/acceptance/deployments-list-test.ts [hunk 8]
```diff
@@ -7,29 +7,55 @@ import { setupMirage } from 'ember-cli-mirage/test-support';
...
+  test('visiting deployments page redirects to latest', async function (assert) {
     let project = this.server.create('project', { name: 'microchip' });
     let application = this.server.create('application', { name: 'wp-bandwidth', project });
     this.server.createList('deployment', 3, 'random', { application });
 
     await page.visit();
 
     assert.equal(page.list.length, 3);
-    assert.equal(currentURL(), url);
+    assert.equal(currentURL(), redirectUrl + 3);
```
Comment (jgwhite) [inline ui/tests/acceptance/deployments-list-test.ts:34]: I’d be tempted to wrap some quotes around that 3 just to make it clear it’s an identifier, not a magic number.

```suggestion
    assert.equal(currentURL(), redirectUrl + '3');
```

File: ui/tests/acceptance/deployments-list-test.ts [hunk 9]
```diff
@@ -7,29 +7,55 @@ import { setupMirage } from 'ember-cli-mirage/test-support';
...
+  });
+
+  test('empty deployments list provides empty state ui', async function (assert) {
+    let project = this.server.create('project', { name: 'microchip' });
+    this.server.create('application', { name: 'wp-bandwidth', project });
+
+    await page.visit();
+
+    assert.equal(page.list.length, 0);
+    assert.equal(currentURL(), emptyStateUrl);
```
Comment (jgwhite) [inline ui/tests/acceptance/deployments-list-test.ts:44]: Worth asserting that we display some sort of empty state element?

```ts
assert.dom('.empty-state').exists();
```

**Review by jgwhite — CHANGES_REQUESTED** [review]
Looking so good! I’ve made a few superficial comments, but certainly no structural changes needed.

File: ui/app/styles/_variables.scss (hunk 4 above)
Comment (almonk) [reply ui/app/styles/_variables.scss:25]: yep – I was going to call this out. It should probably be a lighter gray

File: ui/app/styles/_layout.scss [hunk 10]
```diff
@@ -51,23 +50,53 @@ aside {
   padding-top: scale.$lg-6;
 }
 
+.grid {
```
Comment (gregone) [inline ui/app/styles/_layout.scss:53]: The use of CSS `grid` is awesome. But since we may eventually have multiple grid setups in the future, the name of this class feels very "generic". Could we consider something like `.grid-menu-with-panel` (or other) to be more descriptive?

File: ui/app/styles/components/empty-state.scss [hunk 11]
```diff
@@ -10,6 +10,7 @@
   border-color: rgb(var(--border));
   border-radius: 2px;
   padding: scale.$lg-4;
+  min-height: 526px;
```
Comment (gregone) [inline ui/app/styles/components/empty-state.scss:13]: can we use `vh` instead of pixels here?

File: ui/app/templates/workspace/projects/project/app/deployment.hbs [hunk 12]
```diff
@@ -1,84 +1,44 @@
...
-  </Section>
-{{/if}}
-
-{{outlet}}
+  {{/if}}
+    <div class="panel">
+      {{outlet}}
+    </div>
+  </div>
+{{/let}}
```
Comment (gregone) [inline ui/app/templates/workspace/projects/project/app/deployment.hbs:44]: nit: newline (sorry)

File: ui/app/templates/workspace/projects/project/app/deployment/deployment-seq.hbs [hunk 13]
```diff
@@ -0,0 +1,87 @@
+{{page-title (concat "Deployment" " v" @model.sequence)}}
+{{#if (not-eq this.target.currentRouteName "workspace.projects.project.app.deployment.deployment-seq.resource")}}
+  <PanelHeader @artifact="deployment" @sequence={{@model.sequence}}>
+    <:actions>
+      <div class="button-group">
+        {{#if @model.preload.deployUrl}}
+        <ExternalLink
```
Comment (gregone) [inline ui/app/templates/workspace/projects/project/app/deployment/deployment-seq.hbs:7]: indentation inside `{{#if}}` block

File: ui/app/routes/workspace/projects/project/app/deployment.ts (hunk 1 above)
Comment (sabrinako) [reply ui/app/routes/workspace/projects/project/app/deployment.ts:19]: I did, it didn't automatically work with the code as it is. I'll try again though, probably a small fix to get it working that I just looked over

File: ui/app/routes/workspace/projects/project/app/deployment.ts (hunk 3 above)
Comment (sabrinako) [reply ui/app/routes/workspace/projects/project/app/deployment.ts:15]: After some reading, looks like `afterModel` should be used if the model is necessary for determining where to redirect BUT the redirect is going to a non-child route. `redirect` should be used for a child route, since this prevents the hooks from the original parent route from firing again. Will fix this!

File: ui/app/routes/workspace/projects/project/app/deployment.ts (hunk 1 above)
Comment (jgwhite) [reply ui/app/routes/workspace/projects/project/app/deployment.ts:19]: If it’s a faff then don’t worry about it, the only real benefit it that you’d get to omit the `transition.to.name.includes(...)` predicate.

**Review by jgwhite — APPROVED** [review]
Changes all look great. From my perspective, this looks ready to merge.

**Review by gregone — APPROVED** [review]
Looking good! I have a comment about what I think is a UI bug (see below), but I don't think it's related.

**Comment by gregone** [comment]
@sabrinako Possibly not related:
Screen Shot 2021-11-25 at 15 36 42

On the builds page, the build time badges are flowing below the item. I believe this could be because we remove the `display: flex` on `app-item`

**Comment by gregone** [comment]
A few more comments: cc @almonk 
Screen Shot 2021-11-25 at 15 47 41

**Comment by sabrinako** [comment]
## Comments Addressed (not including comments addresssed before 11/29)

This is mainly for me but also transparency on what might be pushed to future work

### @almonk 
- [x] Badge styling
- [x] Gray well styling (logs + resources table)
- [x] Text truncation (and title added to link element)
  - [x] Sidebar
  - [x] Resources table
- [ ] List items in Overview equal distance
- [ ] Resizing behavior
- [ ] Deployment list info
- [ ] Mutable deployment list info

### @jgwhite
- [ ] Dark mode selected list item

### @gregone 
- [ ] Empty state height as `vh`
- [ ] Scrollable list
- [ ] `Display destroyed deployments` button match design

**Comment by jgwhite** [comment]
Cool to see Percy playing its part on this PR!

**Comment by gregone** [comment]
Sorry for being misleading, as discussed in Zoom, let's drop the `vh` change

**Comment by jgwhite** [comment]
🎉
