### PR TITLE
Minor runner install fixes

### LINKED ISSUE #3678: Runner install w/o cluster name errs in an unhelpful way (AWS ECS)
**Describe the bug**
When running runner install w/o a cluster name, the err is not helpful. 

```
$ waypoint runner install \                 
  -platform=ecs \
  -server-addr=api.hashicorp.cloud:443 \
  -ecs-runner-image=ghcr.io/hashicorp/waypoint/alpha \
  -ecs-region=us-west-2
✓ Finished connecting to: api.hashicorp.cloud:443
❌ Installing runner...
✓ Networking setup
✓ EFS ready
✓ Found existing IAM role to use: waypoint-runner-execution-role
✓ Found existing IAM role to use: waypoint-runner
✓ Using existing log group
❌ Using existing security group: waypoint-server-security-group
! Error installing runner: ClusterNotFoundException: 
```

**Expected behavior**
I would expect either the runner to create a sane cluster name by default or err saying to provide a cluster name.

**Waypoint Platform Versions**
* Waypoint CLI Version:
CLI: v0.9.1 (9562f453c)

### PR DESCRIPTION
**Pull request by paladin-devops**
Fixes #3678 #3680, and #3681.

### CODE REVIEW

File: internal/cli/runner_install.go [hunk 1]
```diff
@@ -160,7 +160,7 @@ func (c *RunnerInstallCommand) Run(args []string) int {
 	p, ok := runnerinstall.Platforms[strings.ToLower(platform[0])]
 	if !ok {
 		c.ui.Output(
-			"Error installing server into %q: unsupported platform",
+			"Error installing runner into %q: unsupported platform",
```
Comment (briancain) [inline internal/cli/runner_install.go:163]: Whoopsie, nice catch!

File: internal/runnerinstall/ecs.go [hunk 2]
```diff
@@ -114,14 +115,20 @@ type EcsConfig struct {
 	CPU               string   `hcl:"runner_cpu,optional"`
 	Memory            string   `hcl:"memory_cpu,optional"`
 	RunnerImage       string   `hcl:"runner_image,optional"`
-	Cluster           string   `hcl:"cluster,optional"`
+	Cluster           string   `hcl:"cluster,required"`
```
Comment (briancain) [inline internal/runnerinstall/ecs.go:118]: Maybe we should group up required params?

**Review by briancain — APPROVED** [review]

File: internal/cli/runner_install.go (hunk 1 above)
Comment (paladin-devops) [reply internal/cli/runner_install.go:163]: Ty @cicoyle !
