### PR TITLE
builtin/docker: Do not require `resources` for task launch config

### LINKED ISSUE #3485: Docker: The Docker task launcher expects a `resources` block when it shouldn't
**Describe the bug**

When attempting to launch a `docker` task with no configuration for the task launcher, every task fails expecting a `resources` block to exist. It shouldn't be required, but the plugin thinks it is.

```
brian@localghost:waypoint λ waypoint job inspect 01G661XCMS5YK40CZSMPV8XT0A                                                                                                                                                                                                                          ±[main]

» Job Configuration
             ID: 01G661XCMS5YK40CZSMPV8XT0A
      Operation: Init
  Target Runner: 01G661XCMS7CVSC9NZ4HZ5HVFG
      Workspace: default
        Project: go-gitops-1

» Job Results
          State: Error
  Error Message: Job dependency "01G661XCMWA8RTF06B9KZXFT39" errored: plugin.hcl:1,1-1: Missing resources block; A resources block is required.
```


**Steps to Reproduce**

Do a `waypoint server install -platform=docker` so that you get a default runner profile that looks like:

```
brian@localghost:docker-remote-registry λ waypoint runner profile inspect docker                                                                                        ±[main]

» Runner profile:
                   Name: docker
                     ID: 01G661RHTV2ZNFAC5SNWMBK583
                Default: true
                OCI URL: waypoint-odr:dev
            Plugin Type: docker
          Target Runner: *
  Environment Variables: map[]
```

Then attempt to do a on-demand runner based deployment, and you should receive an error saying that a `resources` block is required when it shouldn't be.

**Expected behavior**

Users shouldn't have to specify a `resources` block to use the Docker task launcher.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: [cbc6c82](https://github.com/hashicorp/waypoint/commit/cbc6c820bff516ae9f4982aaed5bbeee6b33b477)
* Waypoint Server Platform and Version: [cbc6c82](https://github.com/hashicorp/waypoint/commit/cbc6c820bff516ae9f4982aaed5bbeee6b33b477)
* Waypoint Plugin: `docker`

**Additional context**

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, the task launcher was expecting `Resources` to be
a required plugin config option despite it not actually being required.
This was due to the `TaskResources` field being expected to exist in a
task plugin despite being optional. The fix, similar to how we handle
resource plugin configs in kubernetes, is to make the Resources block a
pointer so that when it's unset, the plugin config parser doesn't expect
it to be required.

Fixes #3485

### CODE REVIEW

File: builtin/docker/task.go [hunk 1]
```diff
@@ -369,14 +369,19 @@ func (b *TaskLauncher) StartTask(
...
 		memory, err = goUnits.FromHumanSize(b.config.Resources.MemoryLimit)
 		if err != nil {
 			return nil, err
 		}
 	}
 
+	if b.config.Resources != nil {
+		cpuShares = b.config.Resources.CpuShares
+	}
+
```
Comment (xiaolin-ninja) [inline builtin/docker/task.go:384]:
```suggestion
	if b.config.Resources != nil {
	         if b.config.Resources.MemoryLimit != "" {
		         memory, err = goUnits.FromHumanSize(b.config.Resources.MemoryLimit)
		         if err != nil {
			        return nil, err
			 }
		}
		
		cpuShares = b.config.Resources.CpuShares
	}
```

**Review by izaaklauer — APPROVED** [review]

**Review by krantzinator — APPROVED** [review]
+1 for @xiaolin-ninja 's suggested change
🎉
