### PR TITLE
server: Ensure `RunPipeline` api returns correct order for `AllJobIds` for pipelines with embedded pipeline graphs

### LINKED ISSUE #3869: embedded pipelines: RunPipeline occasionally returns wrong order of JobIds
**Describe the bug**

Under certain conditions, the slice of JobIds returned from `RunPipeline` is out of order for what order the jobs are actually running in. This means the `waypoint pipeline run` CLI reads the job streams in the wrong order. The good news is the actual job dependencies are right and run in the proper order, it just means the CLI streams them in the wrong order.

**Steps to Reproduce**

Make a pipeline that has two embedded pipeline steps back to back:

```hcl
pipeline "simple-nested" {
  step "here-we-go" {
    image_url = "localhost:5000/waypoint-odr:dev"

    use "exec" {
      command = "echo"
      args    = ["lets try a nested pipeline"]
    }
  }

  step "deploy" {
    workspace = "test"

    pipeline "deploy" {
      step "build" {
        use "build" {
        }
      }
      step "deploy" {
        use "deploy" {
        }
      }
      step "release" {
        use "release" {
        }
      }
    }
  }

  step "deploy-prod" {
    workspace = "prod"

    pipeline "deploy-prod" {
      step "build" {
        use "build" {
        }
      }
      step "deploy" {
        use "deploy" {
        }
      }
      step "release" {
        use "release" {
        }
      }
    }
  }
}
```

If you initialize a pipeline and run `waypoint task list` you'll see the jobs run in order. Sometimes, but not every time, RunPipeline will return an out-of-order list of JobIds so the pipeline run CLI streams them in the wrong order.

**Expected behavior**

The RunPipeline API should return the correct order of JobIds.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.10.0
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

### PR DESCRIPTION
**Pull request by briancain**
This pull request fixes a bug where the `RunPipeline` API was returning the wrong order of `AllJobIds` based on how it constructed and sorted the full pipeline graph. This resulted in the jobstream client reading pipeline jobs out of order from the actual execution order that the jobs ran in. It also adds additional unit tests that check the expected order of job ids to steps.

Fixes https://github.com/hashicorp/waypoint/issues/3869

### CODE REVIEW

File: pkg/server/singleprocess/service_pipeline_test.go [hunk 1]
```diff
@@ -1077,6 +1077,332 @@ func TestServicePipeline_Run(t *testing.T) {
...
+			},
+		}
+
+		// Create, should get an ID back
+		_, err = client.UpsertPipeline(ctx, &pb.UpsertPipelineRequest{
+			Pipeline: embedPipeline,
+		})
+		require.NoError(err)
+
+		// Create another pipeline that references the first one
```
Comment (paladin-devops) [inline pkg/server/singleprocess/service_pipeline_test.go:1310]: The pipeline created on L1312 looks like it contains two exec steps, and doesn't reference the first pipeline.

File: pkg/server/singleprocess/service_pipeline_test.go [hunk 2]
```diff
@@ -1077,6 +1077,332 @@ func TestServicePipeline_Run(t *testing.T) {
...
+			},
+		}
+
+		// Create, should get an ID back
+		pipeResp, err := client.UpsertPipeline(ctx, &pb.UpsertPipelineRequest{
+			Pipeline: pipeline,
+		})
+		require.NoError(err)
+
+		// Create another pipeline that references the first one
```
Comment (paladin-devops) [inline pkg/server/singleprocess/service_pipeline_test.go:1273]: The pipeline created on L1275 looks like it contains two exec steps, and doesn't reference the first pipeline (I assume "the first pipeline" is referring to the one created on L1218).

File: pkg/server/singleprocess/service_pipeline.go [hunk 3]
```diff
@@ -98,7 +98,7 @@ func (s *Service) RunPipeline(
 
 	// Get the graph for the steps so we can get the root. We enforce a
 	// single root so the root is always the first step.
-	stepGraph, nodeToStepRef, err := s.pipelineGraphFull(ctx, log, nil, "",
+	stepGraph, nodeToStepRef, err := s.pipelineGraphFull(ctx, log, nil, "", nil,
```
[the remark this answers is not in the document]
Comment (evanphx) [reply pkg/server/singleprocess/service_pipeline.go:101]: Correct

**Review by evanphx — APPROVED** [review]

File: pkg/server/singleprocess/service_pipeline.go [hunk 4]
```diff
@@ -530,9 +534,19 @@ func (s *Service) pipelineGraphFull(
 			// Add an edge to the parent step as an implicit dependency
```
[the remark this answers is not in the document]
Comment (briancain) [reply pkg/server/singleprocess/service_pipeline.go:534]: Ah, I can delete this! The tests this PR is adding is essentially this TODO

File: pkg/server/singleprocess/service_pipeline_test.go (hunk 2 above)
Comment (briancain) [reply pkg/server/singleprocess/service_pipeline_test.go:1273]: These are just bad copy/paste comments 😄 Will remove

Comment (paladin-devops) [reply pkg/server/singleprocess/service_pipeline_test.go:1273]: Gotcha! I thought that maybe these pipelines needed to refer to the other one, and that this test _could_ have been misleadingly passing for that reason 😄

**Review by paladin-devops — APPROVED** [review]
Looks awesome! Re-reading and "re-understanding" `pipelineGraphFull` since the initial merge of pipelines was fun 😄
