### PR TITLE
Fix `nomad-jobspec-canary` plugin status

### LINKED ISSUE #3476: Incorrect "created resource" in Nomad release
**Describe the bug**
Several times now, Waypoint has gotten confused and claimed it has created a pre-existing job on my Nomad cluster.

Note: this may be related to my jobspec having canary=1, and me forgetting to use -prune=false -- but I would still consider it incorrect and possibly dangerous behavior.

**Steps to Reproduce**
1. waypoint install -platform=nomad -accept-tos \
  -nomad-host=https://nomad.service.consul:4646 \
  -nomad-host-volume=waypoint-data \
  -nomad-dc=skynet -nomad-consul-datacenter=skynet \
  -runner=false
2. waypoint ui -authenticate
3. waypoint init
4. waypoint up

```
project = "monolith"

# An application to deploy.
app "monolith" {
  build {
    use "docker" {}

    registry {
      use "docker" {
        image = "dockreg.bytemonkey.org/monolith"
        tag = gitrefpretty()
      }
    }
  }

  deploy {
    use "nomad-jobspec" {
      jobspec = templatefile("${path.app}/etc/monolith.nomad.tpl")
    }
  }

  release {
    use "nomad-jobspec-canary" {
      groups = ["monolith"]
    }
  }
}
```

related jobspec:
https://github.com/jhillyerd/monolith/blob/7c56a0d44aec960f8acc123e6befa8a71c6c6385/etc/monolith.nomad.tpl

**Expected behavior**
Listed resources created by deployment & release to be equivalent.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version: 0.8.2
* Waypoint Server Platform and Version: nomad
* Waypoint Plugin: docker, nomad-jobspec

**Additional context**
I will re-run with -prune=false and see if I get the same result.

Note `gitea` claimed resource in screenshot, which is unrelated to this codebase and not deployed with waypoint.

waypoint-gitea

### PR DESCRIPTION
**Pull request by paladin-devops**
Closes #3476.

### CODE REVIEW

File: builtin/nomad/canary/releaser.go [hunk 1]
```diff
@@ -251,33 +255,17 @@ func (r *Releaser) resourceJobStatus(
...
-		s.Update("No job was found")
-		s.Status(terminal.StatusError)
-		s.Done()
-		s = sg.Add("")
-
-		jobResource.Name = state.Name
-		jobResource.Health = sdk.StatusReport_MISSING
-		jobResource.HealthMessage = sdk.StatusReport_MISSING.String()
+	if err != nil && job == nil {
+		return err
```
Comment (briancain) [inline builtin/nomad/canary/releaser.go:268]: Should we still be setting the health options here on error?

Comment (paladin-devops) [reply builtin/nomad/canary/releaser.go:271]: We should! Just added that back.

The change to this block also fixed a bug I saw where we continued on error and reported success.

**Review by briancain — APPROVED** [review]
🐦 🎉 looks good!
