### PR TITLE
serverinstall/k8s: Prevent double runner profiles with Helm install

### LINKED ISSUE #3832: `waypoint install` now sets up two runner profiles, ignores requested ODR/Server image
**Describe the bug**

A fresh `waypoint install` with the k8s platform ends up with two runner profiles.

```
brian@ubuntu:waypoint-tetris λ waypoint install -accept-tos -platform=kubernetes -k8s-server-image="localhost:5000/waypoint:dev"
⚠️ Kind cluster detected!

Installing Waypoint to a Kind cluster requires that the cluster has
LoadBalancer capabilities (such as metallb). If Kind isn't configured
in this way, then the install may hang. If this happens, please delete
all the Waypoint resources and try again.
✓ Service "waypoint" is ready
✓ Server bootstrap complete!
✓ Waypoint server installed with Helm!
✓ Configured server connection
✓ Successfully connected to Waypoint server in Kubernetes!
✓ Server installed and configured!
✓ Runner "static" installed
✓ Registered ondemand runner!
✓ Waypoint runner installed with Helm!
✓ Runner "static" adopted successfully.
Waypoint server successfully installed and configured!

The CLI has been configured to connect to the server automatically. This
connection information is saved in the CLI context named "install-1662590313".
Use the "waypoint context" CLI to manage CLI contexts.

The server has been configured to advertise the following address for
entrypoint communications. This must be a reachable address for all your
deployments. If this is incorrect, manually set it using the CLI command
"waypoint server config-set".

To launch and authenticate into the Web UI, run:
waypoint ui -authenticate

Advertise Address: 172.20.0.20:9701
Web UI Address: https://172.20.0.20:9702
brian@ubuntu:waypoint-tetris λ waypoint runner profile list                                                                 ±[main]
Runner profiles
              NAME             | PLUGIN TYPE |                OCI URL                 | TARGET RUNNER | DEFAULT
-------------------------------+-------------+----------------------------------------+---------------+----------
  01GCD1NR5MGSSX2584BYHYFEX5   | kubernetes  | docker.io/hashicorp/waypoint-odr:0.9.1 | *             | yes
  kubernetes-bootstrap-profile | kubernetes  | localhost:5000/waypoint-odr:dev        | *             | yes
```

We should only have the `kubernetes-bootstrap-profile`.

**Steps to Reproduce**

`waypoint install -platform=kubernetes`

**Expected behavior**

Only 1 profile should exist, `kubernetes-bootstrap-profile`.

**Waypoint Platform Versions**
Additional version and platform information to help triage the issue if
applicable:

* Waypoint CLI Version:
* Waypoint Server Platform and Version: (like `docker`, `nomad`, `kubernetes`)
* Waypoint Plugin: (like `aws/ecs`, `pack`, `azure`)

**Additional context**

### PR DESCRIPTION
**Pull request by briancain**
Prior to this commit, the CLI installer would set up two runner profiles: The first one coming from Helm, and the second one coming from our runnerInstall function setting up the bootstrap profile.

Because Helm already sets up a profile, we use that runner profile instead of the bootstrap profile so that we don't install with multiple default runnerp profiles.

Fixes #3832

### CODE REVIEW

**Comment by briancain** [comment]
There's still some issues with this...it seems....


```
brian@ubuntu:waypoint-tetris λ waypoint pipeline run example                                                                        ±[main]

» Running pipeline "example" for application "tetris"
:x: Syncing pipeline configs...
! ondemand runner config not found
! error sentinel
brian@ubuntu:waypoint-tetris λ waypoint runner profile list                                                                         ±[main]
Runner profiles
             NAME            | PLUGIN TYPE |             OCI URL             | TARGET RUNNER | DEFAULT
-----------------------------+-------------+---------------------------------+---------------+----------
  01GCF18ZTG0B2WEEBR7CWZ2EAX | kubernetes  | localhost:5000/waypoint-odr:dev | *             | yes
```

File: internal/cli/install.go [hunk 1]
```diff
@@ -375,9 +367,17 @@ func (c *InstallCommand) Run(args []string) int {
 	s.Update("Server installed and configured!")
 	s.Done()
 
+	// NOTE(briancain): Right now we rely on the fact that only K8S returns a bootstrap
+	// token from the installation interface helper. Since we know helm sets up
+	// a bootstrap job AS WELL AS a runner, we don't need to install another runner
+	// or another runner profile.
 	if c.flagRunner {
+		existingODRConfigSetup := false
+		if bootstrapToken != "" {
```
Comment (briancain) [inline internal/cli/install.go:376]: I don't love this conditional being based on the `bootstrapToken` value being returned from the installer interface. We could add a fourth return value which is a bool that says whether or not it already set up a runner profile? I was trying to keep this change small so went with this instead but if people feel strongly that relying on `bootstrapToken` being set is bad I can add another return bool param.

Comment (xiaolin-ninja) [inline internal/cli/install.go:376]: Is this supposed to be `token != ""` ?

Comment (briancain) [reply internal/cli/install.go:376]: No because `bootstrapToken` is the variable that gets returned from install, where as `token` could of been setup by the CLI bootstrap. See my other comment on the PR about that variable.

**Review by xiaolin-ninja — APPROVED** [review]
Makes sense to me!
