### PR TITLE
plugin/docker: Adding a session when building with buildkit

### LINKED ISSUE #1056: dockerfile.v0: failed to create LLB definition: no active sessions
**Describe the bug**

`waypoint build` fails with:

```
$ waypoint build
✓ Initializing Docker client...
⠦ Building image...
! unable to stream build logs to the terminal: failed to solve with frontend
  dockerfile.v0: failed to create LLB definition: no active sessions
```

**Steps to Reproduce**

Run `waypoint build` with the configuration file below

**Expected behavior**

Waypoint should build the app

**Additional context**

Waypoint 0.2.1.

waypoint.hcl:

```
project = "myproject"

app "myproject-myapp" {

  labels = {
    "service" = "myapp"
    "env" = "dev"
  }

  build {
    use "docker" {
      buildkit = true
    }

    registry {
      use "docker" {
        image = "gcr.io/myproject/myapp"
        tag = "test-0"
      }
    }
  }

  deploy {
    use "google-cloud-run" {
      project  = "myproject"
      location = "us-central1"
      port = 8080
      unauthenticated = true

      capacity {
        memory = 2048
        cpu_count = 1
        max_requests_per_container = 80
        request_timeout = 900
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```

Dockerfile:

```
FROM minimalcompact/thumbor
ENV THUMBOR_PORT=8080
```

### PR DESCRIPTION
**Pull request by izaaklauer**
Fixes #1056

### Why this change?

We observed that we could replicate #1056 on most of the example repos by enabling buildkit. The failure seems to be governed by the FROM image, but isn't consistent - on my machine, `FROM nginx:stable` would be fine, but wouldn't work for @xiaolin-ninja. In any case, the error mentions not having a session, and this change fixes it.

### Future considerations

The docker CLI's usage of moby sessions is _much_ more sophisticated than this. If you're curious, [here](https://github.com/docker/cli/blob/13e4a097ea4cd6df652c5f57f68771fe526fcb1d/cli/command/image/build_buildkit.go#L50)'s where to start reading. Things they are doing that we are not include:

- Generating a session name based on the build context dir, not statically: https://github.com/docker/cli/blob/13e4a097ea4cd6df652c5f57f68771fe526fcb1d/cli/command/image/build_session.go#L34

- Generating a sharedKey that includes randomness but is saved to disk and re-used: https://github.com/docker/cli/blob/13e4a097ea4cd6df652c5f57f68771fe526fcb1d/cli/command/image/build_session.go#L33

- Adding session "Allow" methods, which it looks like turn into GRPC services, which seems to enable non-standard context paths, dockerfile paths, and docker daemon auth methods: (e.x. [here](https://github.com/docker/cli/blob/master/cli/command/image/build_buildkit.go#L167-L177) and [here](https://github.com/docker/cli/blob/master/cli/command/image/build_buildkit.go#L194))

I haven't found any documentation on what any of this session configuration is for, and would rather not dig deep into the moby code to figure it out at this moment. I'm comforted that [img also uses a static session name and blank sharedKey](https://github.com/genuinetools/img/blob/master/client/session.go#L33), and because we only ever connect to a local docker daemon, I don't believe this hurts our security model.

I wouldn't be shocked if some advanced combination of buildkit parameters requires the fancy session configuration. At worst though, this change brings building with buildkit from mostly broken to mostly working, so I think it's worth merging.

Dependency for #1881

### CODE REVIEW

**Review by krantzinator — APPROVED** [review]
I can't speak to the security model but this fix is 🎉

File: builtin/docker/builder.go [hunk 1]
```diff
@@ -341,13 +344,30 @@ func (b *Builder) buildWithDocker(
...
 		Dockerfile: relDockerfile,
 		Tags:       []string{tag},
 		Remove:     true,
 		BuildArgs:  buildArgs,
-	})
+	}
+
+	// Buildkit builds need a session under most circumstances, but sessions are only supported in >1.39
+	if ver == types.BuilderBuildKit && versions.GreaterThanOrEqualTo(cli.ClientVersion(), "1.39") {
+
```
Comment (mitchellh) [inline builtin/docker/builder.go:357]: This empty line is a bit weird.

**Review by mitchellh — APPROVED** [review]
One stupid little comment but this looks good.

File: builtin/docker/builder.go [hunk 2]
```diff
@@ -341,13 +344,30 @@ func (b *Builder) buildWithDocker(
...
+		dialSession := func(ctx context.Context, proto string, meta map[string][]string) (net.Conn, error) {
+			return cli.DialHijack(ctx, "/session", proto, meta)
+		}
+
+		go s.Run(ctx, dialSession)
+		defer s.Close()
+
+		buildOpts.SessionID = s.ID()
+	}
```
Comment (briancain) [inline builtin/docker/builder.go:368]: We should probably log something here in the case where the CLI version isn't supported with sessions but buildkit was requested. It could be inside the StepGroup as a warning so it's visible, or maybe we could pass the `log` through to this func and just log a warning instead.

**Review by briancain — CHANGES_REQUESTED** [review]
Nice job getting this working! I've just got a request for more logging in the unsupported case 👍🏻

**Review by briancain — APPROVED** [review]
